# ZEO configuration file

%define INSTANCE /opt/zope/var/zeo_instances/plinn

<zeo>
  address 9080
  read-only false
  invalidation-queue-size 100
  # pid-filename $INSTANCE/var/ZEO.pid
  # monitor-address PORT
  # transaction-timeout SECONDS
</zeo>

<blobstorage 1>
  blob-dir $INSTANCE/var/blobs
  <filestorage 2>
  path $INSTANCE/var/Data.fs
</filestorage>
</blobstorage>

<eventlog>
  level info
  <logfile>
    path $INSTANCE/log/zeo.log
  </logfile>
</eventlog>

<runner>
  program $INSTANCE/bin/runzeo
  socket-name $INSTANCE/var/zeo.zdsock
  daemon true
  forever false
  backoff-limit 10
  exit-codes 0, 2
  directory $INSTANCE
  default-to-interactive true
  # user zope
  python /usr/local/bin/python
  zdrun /usr/local/lib/python2.7/site-packages/zdaemon/zdrun.py

  # This logfile should match the one in the zeo.conf file.
  # It is used by zdctl's logtail command, zdrun/zdctl doesn't write it.
  logfile $INSTANCE/log/zeo.log
</runner>
